[versions]
axion-plugin = "1.17.0"

[plugins]
#axionReleasePlugin = { id = "pl.allegro.tech.build.axion-release", version.ref = "axion-plugin" }

[libraries]
axionReleasePluginLibrary = { module = "pl.allegro.tech.build:axion-release-plugin", version.ref = "axion-plugin" }
